"""Code quality check using the pipeline engine. Called by: just check"""

import hashlib
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path

from pipeline import run_pipeline

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC = PROJECT_ROOT / "src"

# Stages that record a failure but do not abort the run, so their siblings still
# report. "Ruff Format Check" belongs here: it is the most trivial check in the
# gate, and aborting on it hides the lint and type errors one actually needs.
ALWAYS_RUN_STAGES: set[str] = {
    "Ruff Format Check",
    "Ruff Lint",
    "Mypy",
    "Canon Integrity",
}


def check_canon() -> None:
    """Fail if AGENTS.canon.md was edited by hand.

    The canon is generated by ~/code/_templates/agents_canon and is
    byte-identical in every repository carrying the same profiles. Editing it
    here would fork the house rules silently, so the gate refuses it: change the
    canon there and run 'just agents-sync'. Whether the canon has moved on is a
    different question -- 'just agents-outdated' reports that and does not
    block, because bumping the version is a decision.
    """
    canon = PROJECT_ROOT / "AGENTS.canon.md"
    state = PROJECT_ROOT / ".agents-canon"
    if not canon.exists():
        return
    if not state.exists():
        print("AGENTS.canon.md present but .agents-canon missing")
        sys.exit(1)

    want = ""
    for line in state.read_text(encoding="utf-8").splitlines():
        if line.startswith("sha256: "):
            want = line.removeprefix("sha256: ").strip()
    have = hashlib.sha256(canon.read_bytes()).hexdigest()

    if have != want:
        print("AGENTS.canon.md was edited by hand -- run 'just agents-sync'")
        sys.exit(1)


def make_cmd_runner(cmd: list[str], allowed_codes: set[int] | None = None) -> Callable[[], None]:
    """Create a runner function for simple subprocess commands."""
    if allowed_codes is None:
        allowed_codes = {0}

    def runner() -> None:
        result = subprocess.run(cmd, cwd=PROJECT_ROOT)
        if result.returncode not in allowed_codes:
            sys.exit(result.returncode)

    return runner


def main() -> None:
    is_ci = "--ci" in sys.argv

    all_stages: list[tuple[str, Callable[[], int | None]]] = [
        ("Canon Integrity", check_canon),
        ("Lock-File Check", make_cmd_runner(["uv", "lock", "--check"])),
        (
            "Ruff Format Check",
            make_cmd_runner(["uv", "run", "ruff", "format", "--check", "."]),
        ),
        ("Ruff Lint", make_cmd_runner(["uv", "run", "ruff", "check", "."])),
        ("Mypy", make_cmd_runner(["uv", "run", "mypy", str(SRC)])),
    ]

    if is_ci:
        all_stages.extend(
            [
                (
                    "Unit Tests",
                    make_cmd_runner(
                        [
                            "uv",
                            "run",
                            "pytest",
                            "tests/unit",
                            "-m",
                            "unit",
                            "-q",
                            "-rs",
                        ],
                        allowed_codes={0, 5},
                    ),
                ),
                (
                    "Integration Tests",
                    make_cmd_runner(
                        [
                            "uv",
                            "run",
                            "pytest",
                            "tests/integration",
                            "-m",
                            "integration",
                            "-q",
                            "-rs",
                        ],
                        allowed_codes={0, 5},
                    ),
                ),
                (
                    "System Tests",
                    make_cmd_runner(
                        [
                            "uv",
                            "run",
                            "pytest",
                            "tests/system",
                            "-m",
                            "system",
                            "-q",
                            "-rs",
                        ],
                        allowed_codes={0, 5},
                    ),
                ),
            ]
        )

    passed = run_pipeline(
        all_stages=all_stages,
        always_run_stages=ALWAYS_RUN_STAGES,
    )

    if not passed:
        sys.exit(1)


if __name__ == "__main__":
    main()
