"""The static quality gate, using the pipeline engine. Called by: just check

Static only — no tests run here. The tiers are composed in the justfile
(`ci: check test-all`), because a CI mode here meant the script carried a second
copy of the tier list, and the copy that drifts is the one nobody reads.
"""

import hashlib
import os
import shutil
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path

from common import PROJECT_ROOT
from pipeline import run_pipeline

SRC = PROJECT_ROOT / "src"
PUBLICATION = PROJECT_ROOT / "publication"

# The hand-written Typst. Anything a freeze step generates, and anything an
# overlay vendors into publication/lib, is deliberately not listed here.
TYPST_HANDWRITTEN = [
    PUBLICATION / "main.typ",
    PUBLICATION / "config.typ",
    PUBLICATION / "chapters",
]

# Stages that record a failure but do not abort the run, so their siblings still
# report. "Ruff Format Check" belongs here: it is the most trivial check in the
# gate, and aborting on it hides the lint and type errors one actually needs.
ALWAYS_RUN_STAGES: set[str] = {
    "Ruff Format Check",
    "Ruff Lint",
    "Mypy",
    "Canon Integrity",
    "Copier Source",
    "Typst Format Check",
}


def check_canon() -> None:
    """Fail if AGENTS.canon.md was edited by hand.

    The canon is generated by ~/code/_templates/agents_canon and is
    byte-identical in every repository carrying the same profiles. Editing it
    here would fork the house rules silently, so the gate refuses it: change the
    canon there and run 'just canon-pull'. Whether the canon has moved on is a
    different question -- 'just canon-outdated' reports that and does not
    block, because bumping the version is a decision.
    """
    canon = PROJECT_ROOT / "AGENTS.canon.md"
    state = PROJECT_ROOT / ".agents-canon"
    if not canon.exists():
        return
    if not state.exists():
        print("AGENTS.canon.md present but .agents-canon missing")
        sys.exit(1)

    want = ""
    for line in state.read_text(encoding="utf-8").splitlines():
        if line.startswith("sha256: "):
            want = line.removeprefix("sha256: ").strip()
    have = hashlib.sha256(canon.read_bytes()).hexdigest()

    if have != want:
        print("AGENTS.canon.md was edited by hand -- run 'just canon-pull'")
        sys.exit(1)


def check_copier_source() -> None:
    """Fail if an answers file points at a template directory that is not there.

    `_src_path` records the local path of the template repository, so that a
    template and a project generated from it can be edited in the same sitting
    without a `git push` in between. The price of that choice is exactly one
    failure mode: moving or renaming a template repository breaks every project
    built from it.

    Checking it here turns that into a named file and a path at gate time,
    instead of a `Local template must be a directory.` abort weeks later in the
    middle of a `copier update`. The fix is a `sed` over the answers files.

    Remote sources are left alone -- they are valid, just not the default.
    Skipped outside a git repository: copier refuses to update there at all, so
    the recorded source is inert. That is the throwaway `just probe` case.

    Skipped in CI for the same reason. The recorded path is a directory on the
    developer's machine and is never checked out on a runner, so the check can
    only ever fail there -- and since `ci` is `check test-all`, a failing gate
    means the runner reaches no test at all.
    """
    if not (PROJECT_ROOT / ".git").exists() or os.environ.get("CI"):
        return

    remote_prefixes = ("git@", "git+", "http://", "https://", "ssh://", "gh:", "gl:")
    missing = []
    for path in sorted(PROJECT_ROOT.glob(".copier-answers*.yml")):
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line.startswith("_src_path:"):
                continue
            src = line.removeprefix("_src_path:").strip()
            if src.startswith(remote_prefixes):
                continue
            if not Path(src).expanduser().is_dir():
                missing.append(f"{path.name}: {src}")

    if missing:
        print("template source is gone -- the repository moved or was renamed:")
        for entry in missing:
            print(f"  {entry}")
        print("  fix: sed -i 's|<old>|<new>|' .copier-answers*.yml")
        sys.exit(1)


def check_typst_format() -> None:
    """Fail if a hand-written Typst file is not typstyle-formatted.

    This lives in the gate rather than beside it. `just check-typst` ran the
    same command, but nothing called it -- not `just check`, not `just ci` --
    so a Typst project could sit unformatted indefinitely and only find out
    when someone ran the recipe by hand.

    Only the hand-written files are checked. A freeze step writes generated
    tables and figures into publication/, and an overlay vendors its packages
    into publication/lib -- formatting either would be undone on the next
    generate, or would edit what is not ours.

    typstyle is a standalone binary, not a uv dependency, so a missing one is
    an environment problem and says so instead of failing the formatting.
    On a machine where Homebrew is not on the PATH -- a git hook, a non-login
    shell -- prepend it: PATH=/home/linuxbrew/.linuxbrew/bin:$PATH.
    """
    if shutil.which("typstyle") is None:
        print("typstyle not on PATH -- cannot check Typst formatting")
        print("  install: brew install typstyle")
        print("  in a hook: PATH=/home/linuxbrew/.linuxbrew/bin:$PATH")
        sys.exit(1)

    targets = [str(p) for p in TYPST_HANDWRITTEN if p.exists()]
    if not targets:
        return

    result = subprocess.run(["typstyle", "--check", *targets], cwd=PROJECT_ROOT)
    if result.returncode != 0:
        print("  fix: just fix   (or: typstyle -i publication/)")
        sys.exit(result.returncode)


def make_cmd_runner(cmd: list[str], allowed_codes: set[int] | None = None) -> Callable[[], None]:
    """Create a runner function for simple subprocess commands."""
    if allowed_codes is None:
        allowed_codes = {0}

    def runner() -> None:
        result = subprocess.run(cmd, cwd=PROJECT_ROOT)
        if result.returncode not in allowed_codes:
            sys.exit(result.returncode)

    return runner


def main() -> None:
    all_stages: list[tuple[str, Callable[[], int | None]]] = [
        ("Canon Integrity", check_canon),
        ("Copier Source", check_copier_source),
        ("Lock-File Check", make_cmd_runner(["uv", "lock", "--check"])),
        (
            "Ruff Format Check",
            make_cmd_runner(["uv", "run", "ruff", "format", "--check", "."]),
        ),
        ("Ruff Lint", make_cmd_runner(["uv", "run", "ruff", "check", "."])),
        ("Mypy", make_cmd_runner(["uv", "run", "mypy", str(SRC)])),
    ]

    # Detected rather than templated: this file is copied verbatim, so it cannot
    # ask include_typst. A project generated without the publication layer skips
    # the stage; one that gains it later gets the stage without an edit here.
    if PUBLICATION.is_dir():
        all_stages.append(("Typst Format Check", check_typst_format))

    passed = run_pipeline(
        all_stages=all_stages,
        always_run_stages=ALWAYS_RUN_STAGES,
    )

    if not passed:
        sys.exit(1)


if __name__ == "__main__":
    main()
